# Bootstrap
bootstrap_user: centos

# Git
git_user_name: Joshua Haupt
git_user_email: joshua@hauptj.com

# Firewall
firewall_services:
  - name: ssh
  - name: http
  - name: https
  - name: 6443
    porto: tcp
#  - name: 10248
#    porto: tcp

# Python PIP
pip_package: python3-pip
pip_install_packages:
  - name: docker
  - name: yq

# Docker
docker_edition: 'ce'
#docker_package: "docker-{{ docker_edition }}-3:18.09.1-3.el7"
docker_package_state: latest
docker_install_compose: true
#docker_compose_version: "1.24.1"
docker_users:
  - centos

# Kubernetes
kubernetes_role: master
kubernetes_allow_pods_on_master: true
#kubernetes_version: '1.16'
#kubernetes_version_rhel_package: '1.16.0'
kubernetes_pod_network:
  # Calico CNI.
  cni: 'calico'
  cidr: '192.168.0.0/16'

# Kubernetes Helm
#kubernetes_helm_version: '2.15.2'
kubernetes_helm_platform: 'linux-amd64'
#kubernetes_helm_checksum: 'sha256:a9d2db920bd4b3d824729bbe1ff3fa57ad27760487581af6e5d3156d1b3c2511'
kubernetes_helm_install_dir: '/usr/bin'
#docker_user: centos